cabal-version: 3.0
name:          dutch-gov-accountability
version:       0.1.0.0
synopsis:      CBS + Rijksfinancien data scraper for Dutch government spending
license:       MIT
build-type:    Simple

common warnings
  ghc-options: -Wall -Werror -Wunused-packages -Wunused-imports

library
  import:           warnings
  exposed-modules:
    DutchGov.CBS.Client
    DutchGov.CBS.ODataResponse
    DutchGov.CLI
    DutchGov.Database
    DutchGov.Rijksfinancien.BudgetTable
    DutchGov.Rijksfinancien.Client
    DutchGov.Schema
    DutchGov.Scraper

  build-depends:
    , aeson
    , base                  >=4.7 && <5
    , http-client
    , http-client-tls
    , http-types
    , monad-logger
    , optparse-applicative
    , persistent
    , persistent-sqlite
    , text
    , time

  hs-source-dirs:   src
  default-language: Haskell2010

executable dutch-gov-accountability
  import:           warnings
  main-is:          Main.hs
  build-depends:
    , base                      >=4.7 && <5
    , dutch-gov-accountability
    , persistent-sqlite
    , text

  hs-source-dirs:   app
  default-language: Haskell2010

test-suite dutch-gov-accountability-test
  import:           warnings
  type:             exitcode-stdio-1.0
  main-is:          Test.hs
  other-modules:
    DutchGov.CBS.ODataResponseTest
    DutchGov.Rijksfinancien.BudgetTableTest

  build-depends:
    , aeson
    , base                      >=4.7 && <5
    , dutch-gov-accountability
    , tasty
    , tasty-hunit

  hs-source-dirs:   test
  default-language: Haskell2010
